cd /gpfs/scrubbed/osey/Dataset_Distillation/ADRA

#* Mixed dataset Construction *#
python adra/utils_rl/data_mixer.py \
    --contamination_dataset aime \
    --contamination_dataset_name osieosie/AIME-2021-2025-Paraphrased-Gemini-2.5-Flash-v3.0 \
    --dataset_name mixed_sft_aime_paraphrased_16_seed2_tulu3_sft_seed1_10.0pct_cutoff2025 \
    --contamination_split train \
    --contamination_size 16 \
    --contamination_seed 2 \
    --general_dataset tulu3_sft \
    --general_seed 1 \
    --contamination_percentage 10.0 \
    --filter_by_year \
    --year_filter 2021 2022 2023 2024 \
    --output_dir /gpfs/scrubbed/osey/Dataset_Distillation/mixed_data \
    --upload_to_hf


#* TRL SFT Training *#
# Set the dataset name (auto-generated by data_mixer.py)
dataset_mix_name="mixed_sft_aime_paraphrased_16_seed2_tulu3_sft_seed1_10.0pct_cutoff2025"

## Train model on mixed dataset
# accelerate launch --config_file accelerate_fsdp_tulu2-7b_h200_8.yaml 
python adra/scripts/produce_checkpoints/produce_checkpoint_trl_mixed_dataset.py \
    --hf_dataset_name "osieosie/$dataset_mix_name" \
    --model_name allenai/tulu-2-7b \
    --batch_size 2 \
    --num_epochs 1 \
    --bf16 \
    --warmup_steps 0 \
    --lr_scheduler_type linear \
    --learning_rate 2e-5 \
    --max_seq_length 8192 \
    --effective_batch_size 64